runtime: php
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cuidamos-app
  namespace: '1012186032501'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1012186032501/services/cuidamos-app
  uid: 3274412c-b243-4989-be3f-fe667de68826
  resourceVersion: AAXqnoJGok8
  generation: 2
  creationTimestamp: '2022-10-09T18:49:27.871442Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: cc5f3148-857f-4e76-9085-702b075ba16a
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: greg.jfarias@gmail.com
    serving.knative.dev/lastModifier: greg.jfarias@gmail.com
    client.knative.dev/user-image: gcr.io/cloudrun/placeholder
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: cuidamos-app-placeholder
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1012186032501-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: APP_NAME
          value: Cuidam.os
        - name: APP_ENV
          value: production
        - name: APP_KEY
          value: base64:f5q5FxsO880OyC4+Nw5b3E5nX9cJeOCmYFGLqOIxF+E=
        - name: APP_DEBUG
          value: 'true'
        - name: APP_URL
          value: http://cuidam.os
        - name: JWT_SECRET
          value: siQGwAUwOlRWpLA2mYAHeudxvKUslVf1Y4HNYQOKSpUkRu3xTvjAiTvPjhiThl1W
        - name: JWT_TTL
          value: '86400'
        - name: JWT_REFRESH_TTL
          value: '86400'
        - name: JWT_ALGO
          value: HS256
        - name: SESSION_DOMAIN
          value: cuidam.os
        - name: LOG_CHANNEL
          value: stack
        - name: LOG_DEPRECATIONS_CHANNEL
          value: 'null'
        - name: LOG_LEVEL
          value: debug
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: 34.170.211.242
        - name: DB_PORT
          value: '3306'
        - name: DB_DATABASE
          value: cuidamos
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: 151289Aa!
        - name: FIREBASE_DATABASE_URL
          value: https://tcc-unip-4f80f-default-rtdb.firebaseio.com/
        - name: MEMCACHED_HOST
          value: memcached
        - name: FIREBASE_CREDENTIALS
          value: ./service-account.json
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 2
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2022-10-09T18:49:54.388277Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2022-10-09T18:49:54.190183Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2022-10-09T18:49:54.952783Z'
  latestReadyRevisionName: cuidamos-app-placeholder
  latestCreatedRevisionName: cuidamos-app-placeholder
  traffic:
  - revisionName: cuidamos-app-placeholder
    percent: 100
    latestRevision: true
  url: https://cuidamos-app-krhshzrhra-uc.a.run.app
  address:
    url: https://cuidamos-app-krhshzrhra-uc.a.run.app
